# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazin', '0005_lantmagazine_user_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cumparaturi',
            fields=[
                ('magazin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magazin.Magazin')),
            ],
        ),
    ]
