# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cumparaturi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumparaturi',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cumparaturi',
            name='magazin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magazin.Magazin'),
        ),
    ]
