# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazin', '0005_lantmagazine_user_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100, null=True)),
                ('descriere', models.CharField(max_length=300, null=True)),
                ('data_inceperii', models.DateTimeField(null=True)),
                ('data_sfarsirii', models.DateTimeField(null=True)),
                ('magazin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferte', to='magazin.Magazin')),
            ],
        ),
    ]
