# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='magazin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferte', to='magazin.Magazin'),
        ),
    ]
