# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazin',
            new_name='LantMagazine',
        ),
    ]
