# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_magazin'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='lant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazine', to='magazin.LantMagazine'),
        ),
    ]
